{
 "title": "IotTest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Velocidade do Vento",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"DataLeitura\" AS \"time\",\n  \"VelocidadeVento\"\nFROM \"Meteorologia\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Direção do vento",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 15, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"DataLeitura\" AS \"time\",\n  \"DirecaoVento\"\nFROM \"Meteorologia\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatura ambiente",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kelvin" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"DataLeitura\" AS \"time\",\n  \"Temperatura\",\n  \"Sensacao\"\nFROM \"Meteorologia\"\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Nebulosidade e Umidade relativa",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"DataLeitura\" AS \"time\",\n  \"Nebulosidade\",\n  \"Umidade\"\nFROM \"Meteorologia\"\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 16 },
   "content": "Powered by <span style=\"color: magenta;\">Macnica</span>"
  }
 ]
}